### ISSUE TITLE
Log-In for Users 

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#14]
Info Needed to Track: introduce log-in for tracking the same user data from multiple games

**Comment by adamperer** [comment]
Investigate Google Authentication to solve this feature.

**Comment by yzd1998111** [comment]
Added the google sign in button for the app.

**Comment by adamperer** [comment]
@yzd1998111 Also, show result of logged-in user by renaming Player 1's name and profile to the logged-in user.

**Comment by yzd1998111** [comment]
The loading screen now uses google acct profile image and name as the player's name/profile. If the user does not sign in, the default profile img/name is used. The old way of creating those players had some anti-patterns against React. (Players array is passed from parent to children and modified without making a deep copy, causing many weird bugs when I tried to add this new feature.) I spent quite some time completely fixing them.
