### ISSUE TITLE
Category duplicate within same game 

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#19]
When given representations, should receive for different category. As a user, I had to guess for a train twice within the same game. Should randomize but make sure that not the same. 

<img width="1348" alt="Screen Shot 2019-10-13 at 3 59 35 PM" src="https://user-images.githubusercontent.com/9020517/66723051-9afa5680-ede2-11e9-88d7-f62fff1bd5e5.png">

**Comment by laurafulton** [comment]
Error showed up in different way. As the hinter, I selected parrot but when other guessers shown image it was camera (not my selection). It duplicated image and hints from previous session instead of playing my selection. I think this explains why train was shown twice in a previous play. 
<img width="1120" alt="error repetition camera" src="https://user-images.githubusercontent.com/9020517/67613379-cd109e80-f77a-11e9-95f4-cf2d9ad14a59.PNG">

**Comment by laurafulton** [comment]
Same thing happened with another playthrough. What hinter selects is not being stored and the system resorts to using the same hints and image from last screen. In this case it was for a frog.
<img width="1118" alt="we chose fucking sock" src="https://user-images.githubusercontent.com/9020517/67613611-807a9280-f77d-11e9-858e-2bf48807cb23.PNG">
<img width="1121" alt="2frog" src="https://user-images.githubusercontent.com/9020517/67613615-85d7dd00-f77d-11e9-9eaa-712795e8947c.PNG">

**Comment by yzd1998111** [comment]
The issue might have already been resolved. I looked through the code logic and tested a couple of times and could not replicate this issue. Might need more discussion next week.
