### ISSUE TITLE
Browser Resize

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#21]
Images / Text don’t resize when adjusting browser incrementally (e.g. 100% zoom shows images going off page and at 25% zoom text not longer contained in boxes

**Comment by yzd1998111** [comment]
Needs more discussion for resolution of this issue as I don't know what is the desired behavior.

**Comment by adamperer** [comment]
@laurafulton, would it be possible for you to describe desired behavior to @yzd1998111 ?
