### ISSUE TITLE
error when trying to log-in with google

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#23]
![Screen Shot 2019-11-06 at 11 05 07 AM](https://user-images.githubusercontent.com/1194662/68315212-6a29dc00-0085-11ea-8e09-e1a98b3449b5.png)

**Comment by adamperer** [comment]
https://console.developers.google.com/apis/credentials/oauthclient/423634020815-9pu8kc2gfh3s7rejq6d7k1nmcaqn70d4.apps.googleusercontent.com?project=423634020815

**Comment by adamperer** [comment]
doesn't work with HTTPS

**Comment by yzd1998111** [comment]
now fixed and should be closed. @adamperer
