### ISSUE TITLE
Games does not seem to progress, if you switch to another another tab.

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#33]
Maybe this isn't an issue... but could lead to cheating if people want more time?  We can investigate timestamps later and see if this is happening.

**Comment by yzd1998111** [comment]
This is not a bug. After looking into this, I learned that in chrome when a tab becomes inactive (when user switches to another tab), setInterval function is also paused. To solve this problem, we need to replace all occurrences of setinterval function in the codebase to use real-time to calculate the elapsed time.
