### ISSUE TITLE
Castle Bug

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#34]
Repeated visualizations show up for Castle in the Objects category 

![image](https://user-images.githubusercontent.com/9020517/72941062-12bf1200-3d3e-11ea-8d1d-f77fb928d889.png)
![image](https://user-images.githubusercontent.com/9020517/72941078-1bafe380-3d3e-11ea-9209-a6bddec80f0a.png)

**Comment by yzd1998111** [comment]
This one will be resolved by adam.

**Comment by adamperer** [comment]
I believe I fixed this.  @laurafulton can you confirm?
<img width="1499" alt="Screen Shot 2020-01-29 at 6 11 05 PM" src="https://user-images.githubusercontent.com/1194662/73405774-cbe39600-42c2-11ea-97a5-a03e5101f34c.png">

**Comment by laurafulton** [comment]
Yes, appears to be fixed! <img width="1396" alt="Screen Shot 2020-02-01 at 2 45 04 PM" src="https://user-images.githubusercontent.com/9020517/73598064-721cdf00-4501-11ea-858e-367862bceb12.png">
