### ISSUE TITLE
More accurate choices for Hints 

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#35]
Note that all hint options are not animals (mint + linen narrow down)
<img width="1440" alt="Screen Shot 2020-01-22 at 10 47 19 AM" src="https://user-images.githubusercontent.com/9020517/72941178-5a459e00-3d3e-11ea-9f46-8ff359f03237.png">

Or in this case, not fruits (armadillo, potato, beetles)
<img width="1440" alt="Screen Shot 2020-01-22 at 10 48 37 AM" src="https://user-images.githubusercontent.com/9020517/72941200-65003300-3d3e-11ea-8220-684304e4876b.png">

**Comment by yzd1998111** [comment]
Now shows the hints based on category
