### ISSUE TITLE
Guesses after hint reveal not consistent with category 

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#36]
Guesses after hint revealed not consistent with category revealed in hint (e.g. if hint reveals "fruit" the bot answers are camera and train...not fruits)

<img width="1440" alt="Screen Shot 2020-01-22 at 10 53 03 AM" src="https://user-images.githubusercontent.com/9020517/72941497-1606cd80-3d3f-11ea-8e6e-520c24e560f7.png">

Note: linking this issue to a previous issue which noted and closing that issue.

**Comment by yzd1998111** [comment]
AI only gives answer based on the category from now on.
