### ISSUE TITLE
Create more detailed answer sets for the hint round

### ISSUE THREAD

**Issue by jayolee** [cmuvis/mlint#4]
Currently, I created two answer sets for each category. These answers are used when there's a hint. But because there're only two sets, sometimes it doesn't make sense. For example, if a hint is "it's an object," an automated player might say "strawberry" as an answer.
Not urgent, just better for improving UX.

**Comment by laurafulton** [comment]
Touches on same issue as "Create more detailed answer sets for the hint round #4"

**Comment by laurafulton** [comment]
Created new issue as part of Milestone 2: https://github.com/cmuvis/mlint/issues/36
