### ISSUE TITLE
Firebase - add log for what correct answer

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#43]
Each player guess is tracked but is there a way to track name of animal/object (that the features correspond to) and record this as part of logs. 

This is to check if player text guesses match what the original image is and still record what image was when player fails to get correct.

It is currently unclear for data analysis.

**Comment by yzd1998111** [comment]
The answer is now logged as "answer: xxx" for each guess_round.

**Comment by laurafulton** [comment]
Fixed - Lilian gets correct answer in logs
