### ISSUE TITLE
Instruction before starting guessing 

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#48]
What the 'Round 1' screen currently looks like and what it might look like to remind players of a few things (they type answers, that visualizations don't look exactly like original images, and that they should think broadly). 

Would love feedback/thoughts here.

<img width="863" alt="Screen Shot 2020-04-01 at 12 08 04 PM" src="https://user-images.githubusercontent.com/9020517/78177193-ba864980-742b-11ea-83a5-ffa345e309fd.png">

<img width="863" alt="Screen Shot 2020-04-01 at 12 08 04 PM" src=https://user-images.githubusercontent.com/9020517/78177207-c114c100-742b-11ea-8652-d912423ca826.png>

**Comment by cabreraalex** [comment]
Disregard if this is a hassle, but I really don't think people are going to click "how to play" at the very start - my bet is most people will just click start and try to figure it out.

Might be best to just have specific instructions for each round - You have most of this already in the mockup, but for this one making it clear what they are being shown (another player chose these visualizations for an image), where they have to type answers, and what they are supposed to guess? The framing w/ the strawberry is great!

**Comment by laurafulton** [comment]
Looking into simplifying this and Adam brought up creating gif for home page. Looking into what cards could fit for each round - I think round 0 is selection, round 1 is guess, round 2 is watch, and round 3 is guess (will confirm this and explore relevant hint cards this week)

**Comment by laurafulton** [comment]
@adamperer send scotty dog photos to replace Scotty

**Comment by adamperer** [comment]
@laurafulton here you go:

![image](https://user-images.githubusercontent.com/1194662/79371445-65196480-7f22-11ea-9a1f-dde2431819fc.png)

![image](https://user-images.githubusercontent.com/1194662/79371460-6c407280-7f22-11ea-92da-341bab9f0fee.png)

![image](https://user-images.githubusercontent.com/1194662/79371491-76627100-7f22-11ea-96e0-ba864e4e860b.png)

![image](https://user-images.githubusercontent.com/1194662/79371510-7e221580-7f22-11ea-917d-9adb8d25fd09.png)


![image](https://user-images.githubusercontent.com/1194662/79371833-ff79a800-7f22-11ea-94f2-1f9b431b0ff9.png)

**Comment by laurafulton** [comment]
For guessing rounds. Add text 'It's your turn to guess. Remember...'
![Frame 6 (3)](https://user-images.githubusercontent.com/9020517/79676457-7ed1da80-81b4-11ea-900a-507f9f92ca08.png)

For watch round can add text 'Sit back and watch others guess your image.'  (no visual needed)

**Comment by adamperer** [comment]
There seems to show up now (thanks @kazijawad), but there is no OK button -- it just auto advances after a few seconds.  @laurafulton we wanted to change this, right?

**Comment by laurafulton** [comment]
4x version of scotty dog 
![Frame 7 (1)](https://user-images.githubusercontent.com/9020517/80005907-36573d00-8492-11ea-9246-ceb3c4683a6c.png)

**Comment by laurafulton** [comment]
Dog compolation 
![Frame 7 (2)](https://user-images.githubusercontent.com/9020517/80006320-b7aecf80-8492-11ea-9e8c-540929ed605a.png)

**Comment by laurafulton** [comment]
@kazijawad

**Comment by kazijawad** [comment]
I added this in with the latest commit and correct images.
