### ISSUE TITLE
Leave Page Notification 

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#53]
<img width="934" alt="Screen Shot 2020-04-08 at 12 18 01 PM" src="https://user-images.githubusercontent.com/9020517/78810269-2588d080-7996-11ea-8929-3c8cf6cdf738.png">

@yzd1998111 Kazi is wondering where the code is for this generated notification. Thanks for any help here pointing to how it's generated.

**Comment by yzd1998111** [comment]
This line is complaining about this.uid being null that is assigned when the user signs in. I remember that I was forcing the user to sign in before clicking the start game button so that this bug was not showing.

**Comment by yzd1998111** [comment]
For reference on its usage, this code is taken from 

https://firebase.google.com/docs/auth/web/manage-users

**Comment by kazijawad** [comment]
Thanks I found the issue with this and instead of an alert, it now redirects back to the home page!
