### ISSUE TITLE
only hippo is guessing in watch mode

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#57]
could you make both "fake" players guess?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1194662/79362929-3648c180-7f15-11ea-9835-466fdc22ac8a.png">

**Comment by adamperer** [comment]
Actually, in future rounds, it seems both players do guess.    Can you just double-check its random and not biased towards one fake player guessing more?

**Comment by kazijawad** [comment]
It's definitely random from the code. I guess it just happened to keep getting the hippo on this instance because the randomness is 50/50 since it's only two other players.

`(Math.floor(Math.random() * 2)) + 2;`
