### ISSUE TITLE
crashes (occassionally?) in second round

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#59]
![image](https://user-images.githubusercontent.com/1194662/79379657-381e7f00-7f2d-11ea-9379-39e1b730e48c.png)

**Comment by adamperer** [comment]
bug submitted by @cabreraalex .  did not happen for me.

**Comment by laurafulton** [comment]
Crashed second round as well, different error message <img width="1022" alt="Screen Shot 2020-04-18 at 8 33 36 PM" src="https://user-images.githubusercontent.com/9020517/79676415-f4897680-81b3-11ea-985e-9cbe343998f4.png">

**Comment by kazijawad** [comment]
Fixed both of these issues, it was because the code was based on the old image categories and it was going out of bounds.
