### ISSUE TITLE
Remove Link to Second Game

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#6]
If click "AI Quiz" in header and then "Let's Get Started" get page error <img width="1335" alt="Screen Shot 2019-10-13 at 3 53 14 PM" src="https://user-images.githubusercontent.com/9020517/66722049-46051300-edd7-11e9-8ba2-5c40933394e5.png">
<img width="1133" alt="Screen Shot 2019-10-13 at 3 52 58 PM" src="https://user-images.githubusercontent.com/9020517/66722051-54ebc580-edd7-11e9-8c9d-70bef1f0973b.png">

**Comment by yzd1998111** [comment]
removed
