### ISSUE TITLE
Doesn't work well on mobile:  warn users

### ISSUE THREAD

**Issue by adamperer** [cmuvis/mlint#71]
some screens are unplayable.   perhaps this can be fixed later, but for now, can we warn users to use a bigger screen, before playing?

![image](https://user-images.githubusercontent.com/1194662/81186244-94028380-8f80-11ea-9447-f2a38ec30256.png)

![image](https://user-images.githubusercontent.com/1194662/81186416-c14f3180-8f80-11ea-870b-33c5e83d1e28.png)

![image](https://user-images.githubusercontent.com/1194662/81186402-bdbbaa80-8f80-11ea-89e6-6dcf38ca6520.png)

**Comment by kazijawad** [comment]
Added in the mobile splash screen. It should only pop up for devices smaller than 812px, which is when the game starts to not work properly. It covers all mobile devices and some tablets. Feel free to tweak the message I put in!
