### ISSUE TITLE
Text Overflow on Browser Resize

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#8]
Not top priority as we can standardize browser size for user-testing but still recording as issue:
<img width="443" alt="Screen Shot 2019-10-13 at 4 42 59 PM" src="https://user-images.githubusercontent.com/9020517/66722194-96c93b80-edd8-11e9-9c44-14efd0654634.png">

**Comment by yzd1998111** [comment]
Is this the same issue as #21
