### ISSUE TITLE
Numeric Scores for Representations

### ISSUE THREAD

**Issue by laurafulton** [cmuvis/mlint#9]
For original images, create numeric scores for representations (good, neutral, bad) (1, 0 , -1)  and associate within DB. 

This will be the featureImportanceScore when logging data.

**Comment by laurafulton** [comment]
Do we have a list of which images AI thinks are best?

**Comment by adamperer** [comment]
@laurafulton what type of images?  Input images (e.g. what the explainer selects at the beginning, like a parrot) or the top feature visualizations.
